name: PlugHatia118
version: '${project.version}'
main: me.heinoushare.plughatia118.PlugHatia118
api-version: 1.18
authors: [ Heinoushare ]
description: New Inihatia 1.18 plugin
commands:
  setrace:
    description: set race
    usage: setRace <race>
  speed:
    description: kachow!
    usage: speed
  leap:
    description: bunnyboi
    usage: leap
  givesteelingot:
    description: Steel Ingot
    usage: giveSteelIngot
  givesteelhelmet:
    description: Steel Helmet
    usage: giveSteelHelmet
